#![allow(unused)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(clippy::all)]
// |==========================================================|
// |      WARNING: THIS FILE IS AUTOMATICALLY GENERATED.      |
// |      CHANGES TO IT WILL BE DELETED WHEN REGENERATED.     |
// | IN GENERAL, THIS FILE SHOULD NOT BE MODIFIED IN ANY WAY. |
// |==========================================================|
mod ast;
pub use ast::*;
mod from_pairs;
pub use from_pairs::*;
mod ast_impls;
pub use ast_impls::*;
mod parser;
pub use parser::*;
mod prelude {
    pub use super::*;
    pub use lwb_parser::codegen_prelude::*;
}
